adding test trap

diff --git a/.github/workflows/test_git.yml b/.github/workflows/test_git.yml
--- a/.github/workflows/test_git.yml
+++ b/.github/workflows/test_git.yml
@@ -22,23 +22,41 @@ jobs:
           fetch-depth: 0
       - name: git 1
         run: |
+
+          function retry_push()
+            echo "::Warning::Git push failed, retrying"
+            length=`python -S -c "import random; print(random.randint(10,30))"`
+            sleep $length
+            git remote prune origin
+            git push
+
           sleep 30
           git config user.name github-actions
           git config user.email github-actions@github.com
           #   git config pull.ff only 
           echo ${{ inputs.string}} >> ${{ inputs.string }}
-          git checkout -b ${GITHUB_RUN_ID}
           git add ${{ inputs.string }}
           git commit -m "${{ inputs.string }} - ${GITHUB_RUN_ID}"
-          git push --set-upstream origin ${GITHUB_RUN_ID}
-          git checkout main
-          git pull
-          git merge ${GITHUB_RUN_ID}
+          touch .git/refs/heads/filerefbranch
+          mkdir .git/refs/heads/dirrefbranch
+          trap retry_push - ERR
           git push
-          git push origin --delete ${GITHUB_RUN_ID}
+          trap - ERR
+
+
+
+          # git checkout -b ${GITHUB_RUN_ID}
+          # git add ${{ inputs.string }}
+          # git commit -m "${{ inputs.string }} - ${GITHUB_RUN_ID}"
+          # git push --set-upstream origin ${GITHUB_RUN_ID}
+          # git checkout main
+          # git pull
+          # git merge ${GITHUB_RUN_ID}
+          # git push
+          # git push origin --delete ${GITHUB_RUN_ID}
 
     #   - name: sleep
-    #     run: |
+    #     run: |yW0rnout!
     #       sleep 300
 
     #   - name: git 2
